# Generated by Django 5.2.5 on 2025-08-13 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_budget_user_dailyhousespending_user_income_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyhousespending',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='dailyhousespending',
            name='carryover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailyhousespending',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyhousespending',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spendings', to='tracker.period'),
        ),
        migrations.AlterField(
            model_name='dailyhousespending',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spendings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyhousespending',
            index=models.Index(fields=['user', 'period', 'date'], name='tracker_dai_user_id_0116ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyhousespending',
            constraint=models.UniqueConstraint(fields=('user', 'period', 'date'), name='uniq_user_period_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyhousespending',
            constraint=models.CheckConstraint(condition=models.Q(('spent_amount__gte', 0)), name='spent_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='dailyhousespending',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_daily_limit__gte', 0)), name='limit_gte_0'),
        ),
    ]
