# Generated by Django 5.2.5 on 2025-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_dailyhousespending_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='default_daily_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default daily spending limit for this period', max_digits=12, null=True),
        ),
    ]
