# Generated by Django 5.2.5 on 2025-08-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_period_default_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='notes',
            field=models.TextField(blank=True, help_text='User notes for this period', null=True),
        ),
    ]
